### ISSUE TITLE
Helm Dependencies and values.yaml completion and GoTo-Definition

### ISSUE THREAD

**Issue by zeljkobekcic** [mrjosh/helm-ls#61]
Hey,

I was trying to use the LS in NeoVim but the completion based on dependencies (in the Helm Chart) do not work and also going to the definition. Going to the definition of a value in the dependency would be nice.

A minimal case can be:

`helm create github-issue-chart`

Then copy over this `Chart.yaml`

```yaml
apiVersion: v2
name: test-deploy
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: nginx
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "15.10.29"
```

I would expect this Helm LS to be able to suggest values for `nginx.SOMETHING` inside the `values.yaml`.  This does not work either after running helm dependency update and even after un-tar-ing the tarball (chart).

Here are the logs from `:LspLog`

```
[ERROR][2024-02-20 19:42:22] .../vim/lsp/rpc.lua:734	"rpc"	"/Users/zeljkobekcic/.local/share/nvim/mason/bin/helm_ls"	"stderr"	'{"level":"error","msg":"Error getting chart info for filefile:///private/tmp/test-deploy/values.yamlChart not found for file: file:///private/tmp/test-deploy/values.yaml. Using fallback","time":"2024-02-20T19:42:22+01:00"}\n{"level":"info","msg":"/private/tmp/test-deploy/values.yaml","time":"2024-02-20T19:42:22+01:00"}\n{"level":"info","msg":"helm lint: result for file file:///private/tmp/test-deploy/values.yaml : []","time":"2024-02-20T19:42:22+01:00"}\n{"level":"debug","msg":"Merged diagnostics[]","time":"2024-02-20T19:42:22+01:00"}\n{"level":"info","msg":"Workspace configuration: [{{true yaml-language-server 50 false {map[kubernetes:templates/**] true true}} {values.yaml values.lint.yaml values*.yaml} info}]","time":"2024-02-20T19:42:22+01:00"}\n'
```

I am also using the latest version of `helm-ls`.

Thank you in advance!
